main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

story_7/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.
class Accordion(models.Model):
    title = models.CharField(max_length=255)

class Information(models.Model):
    info_name = models.CharField(max_length=255)
    info_content = models.TextField()
    accordion = models.ForeignKey(Accordion, models.RESTRICT)

main/views.py
from django.shortcuts import render
from .models import Accordion, Information

def home(request):
    data = {
        'list_of_accordion': Accordion.objects.all()
    }
    return render(request, 'main/home.html', data)

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/home.css' %}">
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
<div class="main">

  <ul class="anotherAccord">
    {% for accordion in list_of_accordion %}
    <div class="pack d-flex flex-row justify-content-between">
      <li id="{{ forloop.counter }}" data-id="{{ forloop.counter }}">
        <div>
          <h3>{{ accordion.title }}</h3>
        </div>
        <div class="content">
          {% for info in accordion.information_set.all %}
          <h4>{{ info.info_name }}</h4>
          <p>{{ info.info_content }}</p>
          {% endfor %}
        </div>
      </li>
      <div class="d-flex flex-row thebutton">
        <button onclick="return moveChoiceTo(this, -1)" data-id="{{ forloop.counter }}"><i class="fas fa-arrow-up"></i></button>
        <button onclick="return moveChoiceTo(this, 1)" data-id="{{ forloop.counter }}"><i class="fas fa-arrow-down"></i></button>
      </div>
    </div>
      
    {% endfor %}
  </ul>
</div>


{% endblock content %}
  
{% block js %}
  <script src="{% static 'js/home.js' %}"></script>
  
{% endblock js %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Bootstrap 4 -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  <!-- FontAwesome -->
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/e76dc76644.js" crossorigin="anonymous"></script>
  
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
  
  {% block js %}   
  {% endblock js %}
</body>

</html>